apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-project-demo   #Your app's name
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-project-demo
    spec:
      volumes:
       - name: spanner-creds
         secret:
          secretName: spanner-secret
      containers:
       - name: spring-project-demo  #Your app will be the running container you built
         image: gcr.io/coastal-height-212014/spring-project-demo
         env:
         - name: GOOGLE_APPLICATION_CREDENTIALS
           value: /secrets/app-secrets/coastal-height-212014-ce1c5044b016.json
         volumeMounts:
         - name: spanner-creds
           mountPath: /secrets/app-secrets
           readOnly: true
         imagePullPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: spring-project-demo-load-balancer   #This will be the name of your load balancer
spec:
  selector:
    app: spring-project-demo  #The load balancer will be attached to the app you specify by name here
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:  #Firewall rules
  - 151.140.0.0/16
  - 165.130.0.0/16
  - 207.11.0.0/17
  - 50.207.27.182/32
  - 98.6.11.8/29
